// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for exercises documents */
interface ExercisesDocumentData {
    /**
     * exercise field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.exercise
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    exercise: prismicT.KeyTextField;
    /**
     * resume field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.resume
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    resume: prismicT.KeyTextField;
    /**
     * delay field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.delay
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    delay: prismicT.KeyTextField;
    /**
     * serie field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.serie
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    serie: prismicT.KeyTextField;
    /**
     * repeats field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.repeats
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    repeats: prismicT.KeyTextField;
    /**
     * isometry field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.isometry
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    isometry: prismicT.KeyTextField;
    /**
     * time field in *exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.time
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    time: prismicT.KeyTextField;
    /**
     * grouping field in *exercises*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.grouping
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    grouping: prismicT.RelationField<"grouping">;
    /**
     * conjugates field in *exercises*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.conjugates[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    conjugates: prismicT.GroupField<Simplify<ExercisesDocumentDataConjugatesItem>>;
    /**
     * images field in *exercises*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.images[]
     * - **Tab**: Images
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    images: prismicT.GroupField<Simplify<ExercisesDocumentDataImagesItem>>;
    /**
     * description field in *exercises*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.description
     * - **Tab**: Description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in exercises → conjugates
 *
 */
export interface ExercisesDocumentDataConjugatesItem {
    /**
     * conjugate field in *exercises → conjugates*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.conjugates[].conjugate
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    conjugate: prismicT.RelationField<"exercises">;
}
/**
 * Item in exercises → images
 *
 */
export interface ExercisesDocumentDataImagesItem {
    /**
     * image field in *exercises → images*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: exercises.images[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * exercises document from Prismic
 *
 * - **API ID**: `exercises`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExercisesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ExercisesDocumentData>, "exercises", Lang>;
/** Content for grouping documents */
interface GroupingDocumentData {
    /**
     * title field in *grouping*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: grouping.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * grouping document from Prismic
 *
 * - **API ID**: `grouping`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GroupingDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<GroupingDocumentData>, "grouping", Lang>;
/** Content for home_page documents */
interface HomeDocumentData {
    /**
     * Slice Zone field in *home_page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
}
/**
 * Slice for *home_page → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = MenuSlice;
/**
 * home_page document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for plans documents */
interface PlanDocumentData {
    /**
     * frequency field in *plans*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.frequency
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    frequency: prismicT.KeyTextField;
    /**
     * duration field in *plans*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.duration
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    duration: prismicT.KeyTextField;
    /**
     * start date field in *plans*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.start_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    start_date: prismicT.TimestampField;
    /**
     * end date field in *plans*
     *
     * - **Field Type**: Timestamp
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.end_date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
     *
     */
    end_date: prismicT.TimestampField;
    /**
     * objective field in *plans*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.objective
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    objective: prismicT.RichTextField;
    /**
     * active field in *plans*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: plan.active
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    active: prismicT.BooleanField;
    /**
     * comments field in *plans*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.comments
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    comments: prismicT.RichTextField;
    /**
     * user field in *plans*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: plan.user
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    user: prismicT.RelationField<"users">;
}
/**
 * plans document from Prismic
 *
 * - **API ID**: `plan`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlanDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<PlanDocumentData>, "plan", Lang>;
/** Content for roles documents */
interface RolesDocumentData {
    /**
     * role field in *roles*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: roles.role
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
}
/**
 * roles document from Prismic
 *
 * - **API ID**: `roles`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RolesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<RolesDocumentData>, "roles", Lang>;
/** Content for training documents */
interface TrainingDocumentData {
    /**
     * title field in *training*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: training.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * active field in *training*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: training.active
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    active: prismicT.BooleanField;
    /**
     * comments field in *training*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: training.comments
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    comments: prismicT.RichTextField;
    /**
     * plan field in *training*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: training.plan
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    plan: prismicT.RelationField<"plan">;
    /**
     * Slice Zone field in *training*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: training.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<TrainingDocumentDataSlicesSlice>;
    /**
     * exercises field in *training*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: training.exercises[]
     * - **Tab**: Exercícios
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    exercises: prismicT.GroupField<Simplify<TrainingDocumentDataExercisesItem>>;
}
/**
 * Slice for *training → Slice Zone*
 *
 */
type TrainingDocumentDataSlicesSlice = never;
/**
 * Item in training → exercises
 *
 */
export interface TrainingDocumentDataExercisesItem {
    /**
     * exercise field in *training → exercises*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: training.exercises[].exercise
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    exercise: prismicT.RelationField<"exercises">;
    /**
     * weight field in *training → exercises*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: training.exercises[].weight
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    weight: prismicT.KeyTextField;
}
/**
 * training document from Prismic
 *
 * - **API ID**: `training`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrainingDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TrainingDocumentData>, "training", Lang>;
/** Content for users documents */
interface UsersDocumentData {
    /**
     * name field in *users*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: users.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * user field in *users*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: users.user
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    user: prismicT.KeyTextField;
    /**
     * image field in *users*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: users.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * roles field in *users*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: users.roles[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    roles: prismicT.GroupField<Simplify<UsersDocumentDataRolesItem>>;
}
/**
 * Item in users → roles
 *
 */
export interface UsersDocumentDataRolesItem {
    /**
     * roles field in *users → roles*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: users.roles[].roles
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    roles: prismicT.RelationField<"roles">;
}
/**
 * users document from Prismic
 *
 * - **API ID**: `users`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UsersDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<UsersDocumentData>, "users", Lang>;
export type AllDocumentTypes = ExercisesDocument | GroupingDocument | HomeDocument | PlanDocument | RolesDocument | TrainingDocument | UsersDocument;
/**
 * Item in Menu → Items
 *
 */
export interface MenuSliceDefaultItem {
    /**
     * label field in *Menu → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * url field in *Menu → Items*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.items[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    url: prismicT.LinkToMediaField;
}
/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<MenuSliceDefaultItem>>;
/**
 * Slice variation for *Menu*
 *
 */
type MenuSliceVariation = MenuSliceDefault;
/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSlice = prismicT.SharedSlice<"menu", MenuSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ExercisesDocumentData, ExercisesDocumentDataConjugatesItem, ExercisesDocumentDataImagesItem, ExercisesDocument, GroupingDocumentData, GroupingDocument, HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, PlanDocumentData, PlanDocument, RolesDocumentData, RolesDocument, TrainingDocumentData, TrainingDocumentDataSlicesSlice, TrainingDocumentDataExercisesItem, TrainingDocument, UsersDocumentData, UsersDocumentDataRolesItem, UsersDocument, AllDocumentTypes, MenuSliceDefaultItem, MenuSliceDefault, MenuSliceVariation, MenuSlice };
    }
}
